######################################################################
# Automatically generated by qmake (3.0) Tue Mar 31 11:38:26 2015
######################################################################

TEMPLATE = app
TARGET = AffinityTest
INCLUDEPATH += .
QMAKE_CXXFLAGS += -std=c++11

# Input
HEADERS += affinity.h
FORMS += affinityform.ui
SOURCES += affinity.cpp main.cpp

QT += widgets
